### ISSUE TITLE
Design for itemList, singleItem and singleFile

### ISSUE THREAD

**Issue by RPOD** [runjak/TranscriptionDesk#16]
I changed the raw design of those 3 pages, I would like to get some input if it looks alright, and what changes could be made to make it look better.

**Comment by runjak** [comment]
Imho the mentioned pages look quite good.
I think the more pressing issue would be to get the OpenLayers stuff sorted out so that marking AOIs
offers the agreed categorization and descriptions, the adjacent scans are shown, and already existent AOIs are displayed as well.
I'm closing this issue bc we agreed on the style changes last week.
Please reopen if I'm mistaken and there is more to this.
