### ISSUE TITLE
Build MUFI input system

### ISSUE THREAD

**Issue by runjak** [runjak/TranscriptionDesk#8]
Figure out which MUFI characters we need and implement them in some kind of input system that allows users entering markdown to also input MUFI characters.

**Comment by FTeichmann** [comment]
maybe we should add some kind of dropdown-menu above our input field depending on the number of MUFI characters.

**Comment by ThomasK81** [comment]
Technically you will need all MUFI characters that are accepted by UTF8 (not PUA!). You could resolve this either with a keyboard or by for example holding down the most similar character opens a selection menu.

**Comment by runjak** [comment]
Since the mottie one already has different layouts I guess it won't be too complicated to adjust it…

**Comment by ThomasK81** [comment]
Exactly! Look at this for example: https://github.com/Mottie/Keyboard/blob/master/layouts/hebrew.js

**Comment by FTeichmann** [comment]
The description contains roughtly 750 valid MUFI characters. I could of course build a virtual keyboard to enable the input of all these characters, but I doubt that will be useable and it will 'steal' a lot of screen space. Splitting it into several layers is also bad because then the user would have to search all layers for the symbol he needs.
What would you recommend Thomas?

**Comment by runjak** [comment]
@FTeichmann and me are currently thinking of some filter box that displays a list of possible characters and has an input text that would be used to filter the list of displayed MUFI chars. This would hopefully make it possible to navigate the symbols with more ease. Aside from that [shapecatcher](http://shapecatcher.com/) appears to be a cool thing that could later be used, but currently would imply some overhead to the development effort.
